// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v26.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace video_player_windows {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class WindowsVideoPlayerApi;
  friend class VideoPlayerInstanceApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// Options for creating a new video player.
//
// Generated class from Pigeon that represents data sent in messages.
class CreationOptions {
 public:
  // Constructs an object setting all fields.
  explicit CreationOptions(
    const std::string& uri,
    const flutter::EncodableMap& http_headers);

  // The URI of the video to play.
  const std::string& uri() const;
  void set_uri(std::string_view value_arg);

  // HTTP headers to use when fetching the video.
  const flutter::EncodableMap& http_headers() const;
  void set_http_headers(const flutter::EncodableMap& value_arg);

 private:
  static CreationOptions FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class WindowsVideoPlayerApi;
  friend class VideoPlayerInstanceApi;
  friend class PigeonInternalCodecSerializer;
  std::string uri_;
  flutter::EncodableMap http_headers_;
};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;
 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;
};

// The plugin-level API for the Windows video player.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class WindowsVideoPlayerApi {
 public:
  WindowsVideoPlayerApi(const WindowsVideoPlayerApi&) = delete;
  WindowsVideoPlayerApi& operator=(const WindowsVideoPlayerApi&) = delete;
  virtual ~WindowsVideoPlayerApi() {}
  // Initializes the plugin and disposes all existing players.
  virtual std::optional<FlutterError> Initialize() = 0;
  // Creates a new player and returns its texture ID (used as player ID).
  virtual void Create(
    const CreationOptions& options,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Disposes a player with the given ID.
  virtual std::optional<FlutterError> Dispose(int64_t player_id) = 0;
  // Sets whether audio should mix with other audio sources.
  virtual std::optional<FlutterError> SetMixWithOthers(bool mix_with_others) = 0;
  // Returns the asset file path for the given asset name.
  virtual ErrorOr<std::string> GetAssetUrl(
    const std::string& asset,
    const std::string* package_name) = 0;

  // The codec used by WindowsVideoPlayerApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `WindowsVideoPlayerApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowsVideoPlayerApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    WindowsVideoPlayerApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  WindowsVideoPlayerApi() = default;
};
// The per-player API for the Windows video player.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class VideoPlayerInstanceApi {
 public:
  VideoPlayerInstanceApi(const VideoPlayerInstanceApi&) = delete;
  VideoPlayerInstanceApi& operator=(const VideoPlayerInstanceApi&) = delete;
  virtual ~VideoPlayerInstanceApi() {}
  // Sets whether to automatically loop playback of the video.
  virtual std::optional<FlutterError> SetLooping(bool looping) = 0;
  // Sets the volume, with 0.0 being muted and 1.0 being full volume.
  virtual std::optional<FlutterError> SetVolume(double volume) = 0;
  // Sets the playback speed as a multiple of normal speed.
  virtual std::optional<FlutterError> SetPlaybackSpeed(double speed) = 0;
  // Begins playback if the video is not currently playing.
  virtual std::optional<FlutterError> Play() = 0;
  // Pauses playback if the video is currently playing.
  virtual std::optional<FlutterError> Pause() = 0;
  // Seeks to the given playback position, in milliseconds.
  virtual std::optional<FlutterError> SeekTo(int64_t position) = 0;
  // Returns the current playback position, in milliseconds.
  virtual ErrorOr<int64_t> GetCurrentPosition() = 0;
  // Returns the current buffer position, in milliseconds.
  virtual ErrorOr<int64_t> GetBufferedPosition() = 0;

  // The codec used by VideoPlayerInstanceApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `VideoPlayerInstanceApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    VideoPlayerInstanceApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    VideoPlayerInstanceApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  VideoPlayerInstanceApi() = default;
};
}  // namespace video_player_windows
#endif  // PIGEON_MESSAGES_G_H_
